"""P0.5 — the Kestral Strait cross-tier causal slice.

These prove the chain is REAL: that each declared link carries effect, that removing a link
removes its downstream consequence, that population weighting changes aggregates, and that nothing
accumulates without bound.

The counterfactual tests are the load-bearing ones. A chain that merely produces plausible numbers
proves nothing; a chain where disabling one mechanism demonstrably removes its downstream effect
proves the link exists.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.simulation.engine import MeridianModel
from app.simulation.mechanisms import CHAIN, M_HOUSEHOLD, M_INSURER, M_REROUTE
from app.simulation.rules import kestral_v1 as R
from app.simulation.state import canonical_json
from app.simulation.transitions import TransitionType

SCENARIO_PATH = Path(__file__).resolve().parents[2] / "scenarios" / "kestral-strait.json"
HORIZON = 20


@pytest.fixture()
def scenario() -> dict:
    return json.loads(SCENARIO_PATH.read_text())


@pytest.fixture()
def baseline_scenario(scenario: dict) -> dict:
    """Identical scenario with NO incident — the honest control."""
    return {k: v for k, v in scenario.items() if k != "incidents"}


def run(scenario: dict, ticks: int = HORIZON, seed: int = 88213, enabled=None) -> MeridianModel:
    m = MeridianModel(scenario=scenario, seed=seed, enabled_mechanisms=enabled)
    m.run(ticks)
    return m


# --------------------------------------------------------------------------- #
# 1-2. The incident starts the chain; nothing else does
# --------------------------------------------------------------------------- #
def test_incident_triggers_the_insurer_mechanism(scenario: dict) -> None:
    assert run(scenario).state.chain.insurer_risk > 0.0


def test_without_an_incident_the_chain_never_begins(baseline_scenario: dict) -> None:
    """The strongest guard against a chain that manufactures its own activity.

    An earlier draft failed this: unscaled turnout jitter made collective activity drift upward
    from zero with no incident at all.
    """
    c = run(baseline_scenario, ticks=40).state.chain
    for field in (
        "incident_severity", "insurer_risk", "premium_pressure", "rerouting_level",
        "port_activity_deficit", "employment_pressure", "household_expectation_pressure",
        "narrative_attention", "collective_activity", "political_pressure",
    ):
        assert getattr(c, field) == 0.0, f"{field} moved with no incident: {getattr(c, field)}"
    assert all(v == "AVAILABLE" for v in c.government_options.values())


def test_incident_is_external_input_not_a_rule(scenario: dict) -> None:
    """The incident must arrive from outside, not be generated by the engine."""
    m = run(scenario, ticks=3)
    incidents = [r for r in m.transition_log if r.type is TransitionType.APPLY_INCIDENT]
    assert incidents, "no incident transition recorded"
    assert all(r.origin.value == "external_input" for r in incidents)


# --------------------------------------------------------------------------- #
# 3-10. Every declared link carries effect
# --------------------------------------------------------------------------- #
def test_insurer_risk_drives_insurance_cost_pressure(scenario: dict) -> None:
    c = run(scenario).state.chain
    assert c.insurer_risk > 0.0 and c.premium_pressure > 0.0


def test_cost_pressure_drives_carrier_rerouting(scenario: dict) -> None:
    c = run(scenario).state.chain
    assert c.premium_pressure >= R.REROUTE_TRIGGER_THRESHOLD
    assert c.rerouting_level > 0.0


def test_rerouting_drives_port_and_employment_exposure(scenario: dict) -> None:
    c = run(scenario).state.chain
    assert c.rerouting_level > 0.0
    assert c.port_activity_deficit > 0.0
    assert c.employment_pressure > 0.0


def test_employment_exposure_drives_weighted_cohort_expectations(scenario: dict) -> None:
    m = run(scenario)
    assert m.state.chain.employment_pressure > 0.0
    assert m.state.chain.household_expectation_pressure > 0.0
    assert any(c.economic_concern > 0.0 for c in m.state.cohorts.values())


def test_cohort_response_drives_narrative_and_collective_activity(scenario: dict) -> None:
    c = run(scenario).state.chain
    assert c.household_expectation_pressure > 0.0
    assert c.narrative_attention > 0.0
    assert c.collective_activity > 0.0


def test_narrative_activity_drives_political_pressure(scenario: dict) -> None:
    c = run(scenario).state.chain
    assert c.narrative_attention > 0.0
    assert c.political_pressure > 0.0


def test_political_pressure_changes_government_option_status(scenario: dict) -> None:
    """The end of the chain: societal response must change what the player can do."""
    c = run(scenario).state.chain
    baseline_all_available = {"declare_emergency_powers", "pursue_quiet_diplomacy", "publish_legal_advice"}
    changed = {k for k, v in c.government_options.items() if v != "AVAILABLE"}
    assert changed, f"no option changed despite political_pressure={c.political_pressure}"
    assert changed <= baseline_all_available


def test_emergency_powers_stay_available_in_this_scenario(scenario: dict) -> None:
    """Not every option should fire. A five-day shipping disruption is not an existential crisis.

    This guards against a one-way ratchet dressed up as a causal chain.
    """
    c = run(scenario).state.chain
    assert c.government_options["declare_emergency_powers"] == "AVAILABLE"


def test_options_can_move_back_down(scenario: dict) -> None:
    """Options must be capable of closing again, not only opening."""
    m = run(scenario, ticks=HORIZON)
    assert m.state.chain.government_options["publish_legal_advice"] == "ENABLED"
    # Run far past the incident's decay so pressure falls away.
    m.run(400)
    assert m.state.chain.political_pressure < R.OPTION_PUBLISH_ADVICE_THRESHOLD
    assert m.state.chain.government_options["publish_legal_advice"] == "AVAILABLE"


# --------------------------------------------------------------------------- #
# 11. Counterfactual: disabling a link removes its downstream effect
# --------------------------------------------------------------------------- #
def test_disabling_the_insurer_mechanism_removes_everything_downstream(scenario: dict) -> None:
    """The headline counterfactual. Attribution, not correlation."""
    full = run(scenario)
    without = run(scenario, enabled=[m.id for m in CHAIN if m.id != M_INSURER.id])

    assert full.state.chain.insurer_risk > 0.0
    assert without.state.chain.insurer_risk == 0.0
    # Everything downstream of the insurer collapses with it.
    for field in ("premium_pressure", "rerouting_level", "port_activity_deficit",
                  "employment_pressure", "household_expectation_pressure",
                  "narrative_attention", "collective_activity", "political_pressure"):
        assert getattr(without.state.chain, field) == 0.0, f"{field} survived insurer removal"
    # And the incident itself is unaffected — the link removed is downstream of it.
    assert without.state.chain.incident_severity > 0.0


def test_disabling_rerouting_severs_the_chain_at_that_point(scenario: dict) -> None:
    """Upstream survives, downstream dies — proving where the link sits."""
    without = run(scenario, enabled=[m.id for m in CHAIN if m.id != M_REROUTE.id])
    c = without.state.chain
    assert c.insurer_risk > 0.0, "upstream of the removed link must be unaffected"
    assert c.premium_pressure > 0.0, "upstream of the removed link must be unaffected"
    assert c.rerouting_level == 0.0
    assert c.port_activity_deficit == 0.0
    assert c.employment_pressure == 0.0
    assert c.political_pressure == 0.0


def test_disabling_household_stage_severs_cohorts_from_politics(scenario: dict) -> None:
    without = run(scenario, enabled=[m.id for m in CHAIN if m.id != M_HOUSEHOLD.id])
    c = without.state.chain
    assert c.employment_pressure > 0.0, "upstream survives"
    assert c.household_expectation_pressure == 0.0
    assert c.political_pressure == 0.0
    assert all(co.economic_concern == 0.0 for co in without.state.cohorts.values())


# --------------------------------------------------------------------------- #
# 7. Population weighting
# --------------------------------------------------------------------------- #
def test_population_weighting_is_actually_applied(scenario: dict) -> None:
    """`represents_population` was declared but read by NO code before P0.5.

    The aggregate must equal the population-weighted mean of per-cohort concern.
    """
    m = run(scenario)
    total = sum(c.represents_population for c in m.state.cohorts.values())
    expected = sum(c.economic_concern * c.represents_population for c in m.state.cohorts.values()) / total
    assert m.state.chain.household_expectation_pressure == pytest.approx(expected, abs=1e-9)


def test_population_weighting_materially_changes_the_aggregate(scenario: dict) -> None:
    """Inflating one cohort's population must move the society-wide aggregate."""
    base = run(scenario)
    skewed_scenario = json.loads(json.dumps(scenario))
    # Make the SMALL, HIGHLY-exposed fishing cohort the demographic majority.
    for c in skewed_scenario["cohorts"]:
        if c["cohort_id"] == "coastal-creole-fishing":
            c["represents_population"] = 5_000_000
    skewed = run(skewed_scenario)

    assert skewed.state.chain.household_expectation_pressure > base.state.chain.household_expectation_pressure, (
        "making the most-exposed cohort the majority must raise society-wide pressure"
    )


def test_cohort_intensity_is_independent_of_cohort_size(scenario: dict) -> None:
    """Size affects AGGREGATE MAGNITUDE ONLY — never an individual cohort's intensity.

    The fishing cohort is the smallest and the most exposed. Its own concern must be the highest,
    regardless of how few people it represents.
    """
    m = run(scenario)
    concerns = {cid: c.economic_concern for cid, c in m.state.cohorts.items()}
    populations = {cid: c.represents_population for cid, c in m.state.cohorts.items()}
    fishing = "coastal-creole-fishing"
    assert populations[fishing] == min(populations.values()), "fixture assumption changed"
    assert concerns[fishing] == max(concerns.values()), "smallest cohort must still be most affected"


def test_cohort_concern_tracks_declared_exposure_not_population(scenario: dict) -> None:
    m = run(scenario)
    ordered_by_sensitivity = sorted(
        m.state.cohorts.values(), key=lambda c: c.income_sensitivity, reverse=True
    )
    concerns = [c.economic_concern for c in ordered_by_sensitivity]
    assert concerns == sorted(concerns, reverse=True), "concern must rank by exposure, not size"


# --------------------------------------------------------------------------- #
# 12-13. Determinism and isolation still hold inside the chain
# --------------------------------------------------------------------------- #
def test_repeating_a_run_is_byte_identical(scenario: dict) -> None:
    assert canonical_json(run(scenario).state) == canonical_json(run(scenario).state)


def test_an_unrelated_cohort_does_not_alter_another_cohorts_result(scenario: dict) -> None:
    """P0.4A isolation, verified inside the causal chain rather than in the abstract."""
    base = run(scenario)
    extended_scenario = json.loads(json.dumps(scenario))
    extra = json.loads(json.dumps(extended_scenario["cohorts"][0]))
    extra["cohort_id"] = "newly-added-unrelated-cohort"
    extra["network_position"]["bridges_to"] = []
    extended_scenario["cohorts"].append(extra)
    extended = run(extended_scenario)

    for cid in base.state.cohorts:
        assert extended.state.cohorts[cid].economic_concern == pytest.approx(
            base.state.cohorts[cid].economic_concern, abs=1e-12
        ), f"adding an unrelated cohort moved {cid}"


def test_cohort_evaluation_order_does_not_change_the_outcome(scenario: dict) -> None:
    reordered = json.loads(json.dumps(scenario))
    reordered["cohorts"] = list(reversed(reordered["cohorts"]))
    a, b = run(scenario), run(reordered)
    assert a.state.chain.household_expectation_pressure == pytest.approx(
        b.state.chain.household_expectation_pressure, abs=1e-12
    )
    for cid in a.state.cohorts:
        assert a.state.cohorts[cid].economic_concern == pytest.approx(
            b.state.cohorts[cid].economic_concern, abs=1e-12
        )


# --------------------------------------------------------------------------- #
# 15-19. Boundary, bounds, lags, cooldowns, saturation
# --------------------------------------------------------------------------- #
def test_all_chain_mutations_pass_through_the_transition_service(scenario: dict) -> None:
    m = run(scenario, ticks=5)
    chain_types = {
        TransitionType.SET_CHAIN_SCALAR, TransitionType.SET_COHORT_CONCERN,
        TransitionType.SET_OPTION_STATUS, TransitionType.APPLY_INCIDENT,
        TransitionType.SNAPSHOT_CHAIN_PREVIOUS,
    }
    chain_records = [r for r in m.transition_log if r.type in chain_types]
    assert chain_records
    for r in chain_records:
        if r.applied and r.type is not TransitionType.SNAPSHOT_CHAIN_PREVIOUS:
            assert r.mechanism, f"{r.type} applied without mechanism attribution"
            assert r.mechanism_version, f"{r.type} applied without a mechanism version"


def test_no_scalar_exceeds_its_declared_bounds(scenario: dict) -> None:
    m = MeridianModel(scenario=scenario, seed=88213)
    for _ in range(200):
        m.step()
        c = m.state.chain
        for field in ("incident_severity", "insurer_risk", "premium_pressure", "rerouting_level",
                      "port_activity_deficit", "employment_pressure",
                      "household_expectation_pressure", "narrative_attention",
                      "collective_activity", "political_pressure"):
            v = getattr(c, field)
            assert 0.0 <= v <= 1.0, f"{field} out of bounds at tick {m.tick}: {v}"
        for co in m.state.cohorts.values():
            assert 0.0 <= co.economic_concern <= 1.0


def test_repeated_identical_shocks_do_not_accumulate_without_bound(scenario: dict) -> None:
    """Ten identical incidents must not produce ten times the effect."""
    repeated = json.loads(json.dumps(scenario))
    repeated["incidents"] = [
        {"id": f"shock-{i}", "at_tick": i, "severity": 0.85} for i in range(1, 11)
    ]
    m = run(repeated, ticks=30)
    c = m.state.chain
    assert c.incident_severity <= 1.0
    assert c.political_pressure <= 1.0
    assert c.insurer_risk <= 1.0


def test_extended_no_new_input_run_does_not_accumulate_indefinitely(scenario: dict) -> None:
    """After the incident fades, pressure must fall rather than plateau upward forever."""
    m = run(scenario, ticks=HORIZON)
    peak = m.state.chain.political_pressure
    m.run(500)
    late = m.state.chain.political_pressure
    assert late < peak, f"pressure did not recover: peak={peak} late={late}"
    assert late == pytest.approx(0.0, abs=1e-6), f"pressure never returned to rest: {late}"


def test_rerouting_honours_its_minimum_commitment(scenario: dict) -> None:
    """Cooldown: rerouting cannot unwind the moment pressure dips."""
    m = MeridianModel(scenario=scenario, seed=88213)
    m.run(6)
    assert m.state.chain.rerouting_level > 0.0
    assert m.state.chain.rerouting_ticks_committed > 0


def test_lagged_mechanisms_read_the_previous_tick(scenario: dict) -> None:
    """The insurer declares a one-tick lag, so it cannot react in the incident's own tick."""
    assert M_INSURER.lag_ticks == 1
    m = MeridianModel(scenario=scenario, seed=88213)
    m.step()  # tick 1 — incident arrives
    assert m.state.chain.incident_severity > 0.0
    assert m.state.chain.insurer_risk == 0.0, "insurer reacted in the same tick despite lag=1"
    m.step()  # tick 2 — now it may react
    assert m.state.chain.insurer_risk > 0.0


def test_no_same_tick_causal_cycle(scenario: dict) -> None:
    """Stage order is strictly increasing; feedback waits for the next tick."""
    stages = [m.stage for m in CHAIN]
    assert stages == sorted(stages), "mechanisms are not in non-decreasing stage order"


def test_every_mechanism_declares_its_contract() -> None:
    for m in CHAIN:
        assert m.id and m.version and m.stage_name
        assert m.source_fields and m.target_fields
        assert m.lag_ticks >= 0
        assert m.lifecycle, f"{m.id} declares no lifecycle semantics"


# --------------------------------------------------------------------------- #
# 16. No model or network call on the authoritative path
# --------------------------------------------------------------------------- #
def test_no_llm_or_network_call_in_the_chain(scenario: dict, monkeypatch) -> None:
    """Fail loudly if any mechanism reaches for a socket or the gateway."""
    import socket

    def forbidden(*a, **k):  # pragma: no cover - must never run
        raise AssertionError("the P0.5 authoritative path attempted a network connection")

    monkeypatch.setattr(socket.socket, "connect", forbidden)
    monkeypatch.setattr(socket.socket, "connect_ex", forbidden)

    calls: list[str] = []
    import app.simulation.llm_gateway as gw
    original = gw.propose_action
    monkeypatch.setattr(gw, "propose_action", lambda *a, **k: (calls.append("x"), original(*a, **k))[1])

    m = MeridianModel(scenario=scenario, seed=88213)
    before = len(calls)
    m.chain.run_tick()  # the chain alone, not the whole engine step
    assert len(calls) == before, "a chain mechanism called the LLM gateway"


# --------------------------------------------------------------------------- #
# 13. Causal-parent groundwork (NOT replay)
# --------------------------------------------------------------------------- #
def test_transitions_record_causal_parents_and_sources(scenario: dict) -> None:
    m = run(scenario, ticks=6)
    chain_applied = [
        r for r in m.transition_log
        if r.applied and r.type is TransitionType.SET_CHAIN_SCALAR
    ]
    assert chain_applied
    assert any(r.causal_parents for r in chain_applied), "no causal parent recorded"
    assert any(r.source_fields for r in chain_applied), "no source fields recorded"


def test_draw_references_are_recorded_where_a_draw_was_used(scenario: dict) -> None:
    m = run(scenario, ticks=12)
    with_draws = [r for r in m.transition_log if r.draw_refs]
    assert with_draws, "no transition recorded a draw reference"
    for r in with_draws:
        assert all("hmac-sha256-v1" in ref for ref in r.draw_refs)


# --------------------------------------------------------------------------- #
# 14. Read-only presentation projection
# --------------------------------------------------------------------------- #
def test_projection_is_read_only(scenario: dict) -> None:
    """Rendering a projection any number of times must leave the simulation byte-identical."""
    from app.simulation.projection import project_causal_slice

    m = run(scenario, ticks=12)
    before = canonical_json(m.state)
    for _ in range(25):
        project_causal_slice(m.state, m.transition_log)
    assert canonical_json(m.state) == before


def test_projection_marks_every_value_as_engine_origin(scenario: dict) -> None:
    """Live values must be distinguishable from the C0 fixtures, per record not per page."""
    from app.simulation.projection import project_causal_slice

    p = project_causal_slice(run(scenario).state)
    assert p["origin"] == "engine"
    for group in ("stages", "cohorts", "government_options"):
        assert p[group]
        for entry in p[group]:
            assert entry["origin"] == "engine"
            assert entry["epistemic_status"] == "AUTHORITATIVE"
            # No fabricated confidence: the engine computes, it does not estimate.
            assert entry["confidence"] == "NOT_APPLICABLE"


def test_projection_states_what_is_not_implemented(scenario: dict) -> None:
    from app.simulation.projection import project_causal_slice

    p = project_causal_slice(run(scenario).state)
    for missing in ("replay", "event sourcing", "state hashing", "persistence"):
        assert missing in p["not_implemented"]


def test_projection_exposes_mechanism_attribution_for_each_stage(scenario: dict) -> None:
    from app.simulation.projection import project_causal_slice

    p = project_causal_slice(run(scenario).state)
    for stage in p["stages"]:
        assert stage["mechanism"] and stage["mechanism_version"]
        assert stage["lifecycle"], f"{stage['field']} exposes no lifecycle semantics"


def test_projection_exposes_population_share_without_implying_more(scenario: dict) -> None:
    from app.simulation.projection import project_causal_slice

    p = project_causal_slice(run(scenario).state)
    shares = sum(c["population_share"] for c in p["cohorts"])
    assert shares == pytest.approx(1.0, abs=1e-6)
